name = "Madianapack"
author = "MmeCromatique"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bac2ecfbd0fd5a1147c8a3bd87b43fb3f9ebe186f117d120af2ce3ef3d1ebe58"

[versions]
fabric = "0.18.6"
minecraft = "26.1"

[options]
acceptable-game-versions = ["26.1"]
