name = "Madianapack"
author = "MmeCromatique"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "385e190017248f3e461d2ce1bb3edc1de2d662c581713457b83a264f349e11ac"

[versions]
fabric = "0.18.5"
minecraft = "26.1"
