name = "Madianapack"
author = "MmeCromatique"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eacbf329b936544d3e8026f84b584cc4666867fc62107e53f9896a58e64eebb9"

[versions]
fabric = "0.18.5"
minecraft = "26.1"
